//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Cer_MyCertificate
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CerId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsDrop { get; set; }
        public string Guid { get; set; }
        public string Content { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string CardCode { get; set; }
        public string RealName { get; set; }
    }
}
