//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Cer_Certificate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> IsFreeze { get; set; }
        public Nullable<int> Style { get; set; }
        public Nullable<int> IDColumn { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
