//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    public partial class Dept_Roles
    {
        public int RoleId { get; set; }
        public int TenantId { get; set; }
        public int DeptId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUser { get; set; }
        public int IsDefault { get; set; }
        public int Status { get; set; }
        public int IsDelete { get; set; }
    }
}
