//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Dept_Users
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int TenantId { get; set; }
        public int DeptId { get; set; }
        public string Realname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
        public int Sex { get; set; }
        public Nullable<int> IDType { get; set; }
        public string CardCode { get; set; }
        public string QqNo { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public string Memo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
        public int IsDelete { get; set; }
    }
}
