//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Len_Questions
    {
        public int id { get; set; }
        public string room { get; set; }
        public string problem { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string reply { get; set; }
        public Nullable<System.DateTime> replyTime { get; set; }
        public Nullable<int> isreply { get; set; }
    }
}
