//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Len_UserLearnWare
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int WareId { get; set; }
        public int UserId { get; set; }
        public int WareType { get; set; }
        public Nullable<int> ProgressPercent { get; set; }
        public Nullable<int> AttemptId { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<decimal> LearnTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int SortId { get; set; }
        public Nullable<decimal> PassTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ExamPass { get; set; }
        public Nullable<int> VedioPass { get; set; }
    }
}
