//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Len_UserOrder
    {
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public int IsDelete { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BookBuyId { get; set; }
        public int TenantId { get; set; }
        public Nullable<int> PayType { get; set; }
    }
}
