//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Len_LearningRecord
    {
        public int RecordId { get; set; }
        public int CourseId { get; set; }
        public int UserId { get; set; }
        public int LearnProcess { get; set; }
        public Nullable<System.DateTime> LastLearnTime { get; set; }
        public Nullable<int> LearnPath { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    }
}
