//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class MessageSending
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Type { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime PlanTime { get; set; }
        public string Parameters { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Remarks { get; set; }
        public int SendDegree { get; set; }
    }
}
