//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_Course
    {
        public int CourseId { get; set; }
        public int TenantId { get; set; }
        public int CategoryId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Teacher { get; set; }
        public Nullable<int> Year { get; set; }
        public string FrontImage { get; set; }
        public int IsRecommend { get; set; }
        public string PicUrl { get; set; }
        public int LearnTime { get; set; }
        public int LearnScore { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Validity { get; set; }
        public int IsBilling { get; set; }
        public int Status { get; set; }
        public int IsPublish { get; set; }
        public int IsDelete { get; set; }
        public int IsOpen { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> FromCourseId { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> CerId { get; set; }
        public Nullable<System.DateTime> StartLearning { get; set; }
        public Nullable<System.DateTime> EndLearning { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
