//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CourseEnter
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<int> EnterType { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ValidDay { get; set; }
        public string LearnRecordTags { get; set; }
        public Nullable<int> DeptID { get; set; }
    }
}
