//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_TaskRes
    {
        public int ResId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ResSourceId { get; set; }
        public Nullable<int> ResType { get; set; }
        public int TenantId { get; set; }
        public int IsDelete { get; set; }
    }
}
