//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_Card
    {
        public int Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> SaleNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public string OpenObject { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
