//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CourseWareTree
    {
        public int SortId { get; set; }
        public string SortName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> WareId { get; set; }
        public Nullable<int> OrderNum { get; set; }
    }
}
