//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_Resource
    {
        public int Id { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ResourceCode { get; set; }
        public string ResourceRealname { get; set; }
        public string ResourceName { get; set; }
        public Nullable<int> ResourceSize { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public Nullable<int> ResourceLength { get; set; }
        public string ResourcePath { get; set; }
        public string TeachName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string QiniuLocation { get; set; }
    }
}
