//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CardReturn
    {
        public int Id { get; set; }
        public int SoldId { get; set; }
        public int CardId { get; set; }
        public int DeptId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ReturnCount { get; set; }
        public System.DateTime ReturnTime { get; set; }
    }
}
