//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_BookStorage
    {
        public int Id { get; set; }
        public int TenantId { get; set; }
        public string StorageCode { get; set; }
        public Nullable<int> StorageCount { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> StorageDate { get; set; }
    }
}
