//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CardSoldRecord
    {
        public int Id { get; set; }
        public Nullable<int> SoldId { get; set; }
        public string CardCodePassword { get; set; }
        public Nullable<int> SoldUserId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ActiveUserId { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public Nullable<int> ActiveFlag { get; set; }
    }
}
