//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_BookUserDetials
    {
        public int ID { get; set; }
        public Nullable<int> BookBuyID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ComeFrom { get; set; }
    }
}
