//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CardSold
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> SoldCount { get; set; }
        public Nullable<int> ReturnFlag { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
    }
}
