//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CourseWareToExam
    {
        public int Id { get; set; }
        public int SortID { get; set; }
        public Nullable<int> WareId { get; set; }
        public Nullable<int> ExamId { get; set; }
    }
}
