//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_TeacherBook
    {
        public int BookId { get; set; }
        public int TenantId { get; set; }
        public string BookName { get; set; }
        public string BookCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> BookType { get; set; }
        public string PicUrl { get; set; }
        public string Press { get; set; }
        public string ISBN { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PressTime { get; set; }
        public string Memo { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> Stock { get; set; }
        public int IsDelete { get; set; }
    }
}
