//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CourseWare
    {
        public int WareId { get; set; }
        public int TenantId { get; set; }
        public string WareCode { get; set; }
        public string WareName { get; set; }
        public string Teacher { get; set; }
        public string WareDec { get; set; }
        public string PicUrl { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public int Status { get; set; }
        public int IsPublish { get; set; }
        public int IsDelete { get; set; }
        public int CreaterUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public string Tags { get; set; }
        public Nullable<int> LearnRule { get; set; }
        public Nullable<int> FromWareId { get; set; }
    }
}
