//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Res_CourseWareTreeResource
    {
        public int Id { get; set; }
        public Nullable<int> SortId { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<int> PaperId { get; set; }
        public Nullable<int> TestLength { get; set; }
        public string QuestionIds { get; set; }
        public string QuestionTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> VideoPassLine { get; set; }
        public Nullable<int> WareId { get; set; }
        public Nullable<int> PassType { get; set; }
    }
}
