//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    public partial class Sys_Tenant
    {
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string TenantDesc { get; set; }
        public string TenantCode { get; set; }
        public System.DateTime JoinTime { get; set; }
        public string DomainName { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUser { get; set; }
        public string SkinName { get; set; }
        public string PayAccount { get; set; }
        public string PayKey { get; set; }
        public string PayPartnerID { get; set; }
        public int IsDelete { get; set; }
        public string TenantTitle { get; set; }
        public string TenantLogo { get; set; }
        public string PicUrl { get; set; }
    }
}
