//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Sys_Users
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public int TenantId { get; set; }
        public string Realname { get; set; }
        public string NamePin { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Sex { get; set; }
        public string IDType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string PostTitle { get; set; }
        public string Political { get; set; }
        public string Domicile { get; set; }
        public string Location { get; set; }
        public string HomeAddr { get; set; }
        public string HighestEdu { get; set; }
        public string Tags { get; set; }
        public string QqNo { get; set; }
        public string Weibo { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LoginIp { get; set; }
        public int Status { get; set; }
        public int IsDelete { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public string Mobile { get; set; }
        public string Nation { get; set; }
        public string Provence { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public Nullable<int> TeachYears { get; set; }
        public Nullable<int> IsTeacher { get; set; }
        public string School { get; set; }
        public string Professional { get; set; }
        public string Memo { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> IsVerification { get; set; }
        public Nullable<int> Major { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string Summary { get; set; }
        public Nullable<int> OtherUserid { get; set; }
    }
}
