//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Sys_Notes
    {
        public int NoteId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<int> Type { get; set; }
        public string NoteTitle { get; set; }
        public string NoteContent { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> PublishFlag { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<int> IsTop { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
