//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Sys_Questionnaire
    {
        public int Id { get; set; }
        public int TenantId { get; set; }
        public int CourseId { get; set; }
        public string QuestionText { get; set; }
        public int QuestionType { get; set; }
        public string TopicOptions { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
