//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Sys_Department
    {
        public int DepartmentId { get; set; }
        public int TenantId { get; set; }
        public string DeptName { get; set; }
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CreateUser { get; set; }
        public decimal Credit { get; set; }
        public string DomainName { get; set; }
        public int Status { get; set; }
        public int IsDelete { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PayPassword { get; set; }
        public decimal BackRate { get; set; }
        public Nullable<decimal> SumCredit { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
