//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    public partial class Sys_Config
    {
        public int ConfigId { get; set; }
        public string ConfigCode { get; set; }
        public int TenantId { get; set; }
        public string ConfigName { get; set; }
        public string ConfigValue { get; set; }
    }
}
