//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    public partial class Sys_OperPermission
    {
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public string Controller { get; set; }
        public string AreaName { get; set; }
        public string Action { get; set; }
        public int PermissionType { get; set; }
        public int ParentId { get; set; }
        public string Icon { get; set; }
    }
}
