//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    public partial class Sys_UserMessageContent
    {
        public int MessageId { get; set; }
        public string Title { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int TenantId { get; set; }
    }
}
