//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YangMei.Toolkit.Modle
{
    using System;

    public partial class Tag_relation
    {
        public int id { get; set; }
        public Nullable<int> relId { get; set; }
        public Nullable<int> tagid { get; set; }
        public Nullable<int> tagtype { get; set; }
    }
}
