//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceLog
    {
        public long Id { get; set; }
        public long BId { get; set; }
        public long CompanyId { get; set; }
        public long OrderId { get; set; }
        public Nullable<int> ChangeNumbers { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
