//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallBatchToCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallBatchToCustomer()
        {
            this.CallRemarks = new HashSet<CallRemarks>();
        }
    
        public long Id { get; set; }
        public long BatchId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> BId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<int> CallStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual CallBatch CallBatch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallRemarks> CallRemarks { get; set; }
    }
}
