//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallRemarks
    {
        public long Id { get; set; }
        public Nullable<long> BatchToCustomerId { get; set; }
        public string RealName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<int> CallStatus { get; set; }
        public Nullable<int> Intension { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
    
        public virtual CallBatchToCustomer CallBatchToCustomer { get; set; }
    }
}
