//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerIntention
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public string ProjectName { get; set; }
        public string NewCode { get; set; }
        public Nullable<int> ProjectCity { get; set; }
        public Nullable<int> ProjectArea { get; set; }
        public Nullable<int> BehaviorType { get; set; }
        public Nullable<System.DateTime> BehaviorTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
