//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.CallBatchToCustomer = new HashSet<CallBatchToCustomer>();
            this.CustomerIntention = new HashSet<CustomerIntention>();
            this.BusinessToCustomers = new HashSet<BusinessToCustomers>();
        }
    
        public long Id { get; set; }
        public string RealName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public int IsDelete { get; set; }
        public Nullable<System.DateTime> GenerateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallBatchToCustomer> CallBatchToCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerIntention> CustomerIntention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessToCustomers> BusinessToCustomers { get; set; }
    }
}
