//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class icusEntities : DbContext
    {
        public icusEntities()
            : base("name=icusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<BalanceLog> BalanceLog { get; set; }
        public virtual DbSet<CallBatch> CallBatch { get; set; }
        public virtual DbSet<CallBatchToCustomer> CallBatchToCustomer { get; set; }
        public virtual DbSet<CallRemarks> CallRemarks { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CustomerIntention> CustomerIntention { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Funcs> Funcs { get; set; }
        public virtual DbSet<ImportTelephone> ImportTelephone { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ProjectToArea> ProjectToArea { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VirtualNumbers> VirtualNumbers { get; set; }
        public virtual DbSet<BusinessToCustomers> BusinessToCustomers { get; set; }
        public virtual DbSet<Commission> Commission { get; set; }
    }
}
