//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICusCRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportTelephone
    {
        public long Id { get; set; }
        public string ProjectName { get; set; }
        public string NewCode { get; set; }
        public string UserPhone { get; set; }
        public string ProjectCity { get; set; }
        public string ProjectArea { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> BehaviorTime { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
