//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeOperateLog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Field5 { get; set; }
        public string Field4 { get; set; }
        public string Field3 { get; set; }
        public string Field2 { get; set; }
        public string Field1 { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public System.DateTime OperatorCreateTime { get; set; }
    }
}
